/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories.

SQL Functions Used:
    - Aggregate Functions: SUM(), COUNT(), AVG()
    - GROUP BY, ORDER BY
===============================================================================
*/

-- Find total customers by countries
select cntry, count(customer_key)
from customer_gold_layer
group by cntry
order by cntry;

-- Find total customers by gender
select gender, count(customer_no) 
from customer_gold_layer
group by gender
order by gender;

-- Find total products by category

select category, count(product_key)
from product_gold_layer
group by category;

select * from product_gold_layer where category is null;

-- What is the average costs in each category?
select 
    category,
    AVG(cost) AS avg_cost
from product_gold_layer
group by category ;


-- What is the total revenue generated for each category?
select 
	category,
    sum(sls_price)
from sales_gold_layer as s
left join product_gold_layer as p
on p.product_key = s.product_key
group by category;


-- What is the total revenue generated by each customer?
select 
	s.customer_key,
    c.firstname,
    c.lastname,
    sum(s.sls_price) totalrevenue
from sales_gold_layer as s
left join customer_gold_layer as c
on c.customer_key = s.customer_key
group by s.customer_key, c.firstname, c.lastname
order by totalrevenue desc;

-- What is the distribution of sold items across countries?
select 
	cntry,
    sum(s.quantity)
from sales_gold_layer as s
left join customer_gold_layer as c
on s.customer_key = c.customer_key
group by cntry
order by sum(s.quantity) desc
;

select distinct cntry from customer_gold_layer;